#!/bin/bash

get_container_id() {
    CONTAINER_ID=$(docker ps -f name=dsp-postgres -q)
}

get_container_id

if [ -z "$CONTAINER_ID" ]; then
    echo "No container found with name 'dsp-postgres'"
    echo "Starting container..."
    docker compose up -d
    get_container_id
    if [ -z "$CONTAINER_ID" ]; then
        echo "Failed to start container"
        exit 1
    fi
   
fi

# wait for container to start
while [ -z "$(docker exec $CONTAINER_ID psql -U postgres -c "SELECT 1;" 2>/dev/null)" ]; do
    sleep 1
done

docker exec $CONTAINER_ID psql -U postgres -c "DROP DATABASE vacuum_db;"
