version: '3.9'

services:
    postgres1:
        image: postgres:15.2-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DATABASE=postgres
    postgres2:
        image: postgres:15.2-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DATABASE=postgres
    pgbouncer:
        image: edoburu/pgbouncer
        environment:
            - DB_HOST=postgres1
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_NAME=test
            - MAX_CLIENT_CONN=5000
        ports:
          - 5432:5432