#!/bin/bash

if [ -z "$(command -v curl)" ]; then
    echo "curl is not installed"
    echo "Use 'sudo apt install curl' to install it"
    exit 1
fi


if [ -z "$(command -v unzip)" ]; then
    echo "unzip is not installed"
    echo "Use 'sudo apt install unzip' to install it"
    exit 1
fi

mkdir -p tmp
curl --proto '=https' --tlsv1.2 -sSf -o tmp/demo-small.zip https://edu.postgrespro.ru/demo-small.zip
unzip -o -d tmp/ tmp/demo-small.zip 

get_container_id() {
    CONTAINER_ID=$(docker ps -f name=dsp-postgres -q)
}

get_container_id

if [ -z "$CONTAINER_ID" ]; then
    echo "No container found with name 'dsp-postgres'"
    echo "Starting container..."
    docker compose up -d
    get_container_id
    if [ -z "$CONTAINER_ID" ]; then
        echo "Failed to start container"
        exit 1
    fi
   
fi

# wait for container to start
while [ -z "$(docker exec $CONTAINER_ID psql -U postgres -c "SELECT 1;" 2>/dev/null)" ]; do
    sleep 1
done

docker cp tmp/demo-small-20170815.sql $CONTAINER_ID:/tmp/demo-small.sql
docker exec $CONTAINER_ID psql -U postgres -f /tmp/demo-small.sql

rm -rf tmp